spring:
  application:
    name: access-requester
  #  Datasource
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://db:3306/access-requester?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DATASOURCE_USERNAME:access-requester}
    password: ${DATASOURCE_PASSWORD:iCP3W9ZSccD5}
  #  JPA
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL:update}
  #  Mail
  mail:
    host: ${MAIL_HOST:maildev}
    port: ${MAIL_POST:1025}
    properties:
      mail:
        smtp:
          auth: ${SMTP_AUTH:false}
          starttls:
            enable: ${SMTP_TLS:false}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
#Logging
server:
  error:
    include-message: always
logging:
  file:
    name: ${LOGGING_FILE:./logs/${spring.application.name}.log}
#Security
cors:
  cors-origins: ${CORS_ORIGINS:https://access-requester.dev}
  cors-methods: ${CORS_METHODS:*}
  cors-headers: ${CORS_HEADERS:*}
roles:
  map:
    ADMIN: Administrator
    USERS_MNGT: Users management
    SETTINGS: Settings
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/access-requester?useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    show-sql: true
  mail:
    host: localhost
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file:
    name:
  level:
    td.aboudev: trace
cors:
  cors-origins: '*'