spring:
  application:
    name: access-requester
  #  Datasource
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://db:3306/access-requester?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DATASOURCE_USERNAME:access-requester}
    password: ${DATASOURCE_PASSWORD:iCP3W9ZSccD5}
  #  JPA
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL:update}
  #  Mail
  mail:
    host: ${MAIL_HOST:maildev}
    port: ${MAIL_POST:1025}
    properties:
      mail:
        smtp:
          auth: ${SMTP_AUTH:false}
          starttls:
            enable: ${SMTP_TLS:false}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
# JWT Security
jwt:
  secret: ${JWT_SECRET:31caa6c741b5109f522fc6ca620dc50e8377c0c919c7e3353874aa3c2334cec7}
  expiration: ${JWT_EXPIRATION:3600000} # Time in milliseconds - 3600000 = 1h
  blacklist-clean: ${JWT_BLACKLIST_CLEAN:0 0 1 * * *} # every day at 1 am
#Logging
server:
  error:
    include-message: always
logging:
  file:
    name: ${LOGGING_FILE:./logs/${spring.application.name}.log}
#Security
cors:
  cors-origins: ${CORS_ORIGINS:https://access-requester.dev}
  cors-methods: ${CORS_METHODS:*}
  cors-headers: ${CORS_HEADERS:*}
roles:
  map:
    ADMIN: role.administrator
    USERS_MNGT: role.users_management
    SETTINGS: role.settings
    APP_MNGT: role.app_management
db_referenced_row_error: ${DB_ER_NO_REFERENCED_ROW:1451} # 1451 for mysql8
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/access-requester?useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    show-sql: true
  mail:
    host: localhost
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file:
    name:
  level:
    td.aboudev: trace
cors:
  cors-origins: '*'
jwt:
  blacklist-clean: '0 */5 * * * *'